/** Centralized UI copy for owner-facing (Simple) vs consistent labels */

export const copy = {
  org: {
    homeTitle: "Organization home",
    dashboardEyebrow: "Your organization",
    newPeriod: "New reporting period",
    reportingPeriods: "Reporting periods",
    noPeriodsTitle: "No reporting periods yet",
    noPeriodsBody: "Create a reporting period to upload documents and build your sustainability report.",
    createPeriod: "Create reporting period",
    continue: "Continue",
    provisioningTitle: "Account setup in progress",
    provisioningBody:
      "Your account needs to be linked to an organization by an administrator before you can start reporting.",
  },
  period: {
    hubTitle: "Reporting period",
    dueLabel: "Due",
    onTrack: "On track",
    atRisk: "At risk",
    readiness: "Report readiness",
    traceability: "Traceability score",
    blockingTitle: "What's blocking publish?",
    openReport: "Open report draft",
    exportReport: "Export report",
    continueReview: "Continue review",
    uploadDocuments: "Upload documents",
    evidenceComplete: "Evidence complete",
    tabReadiness: "Readiness",
    tabDocuments: "Documents",
    tabReport: "Report",
    tabEvidence: "Evidence",
  },
  documents: {
    title: "Documents",
    subtitle: "Choose a document type, then upload your source files. Atlas secures each file and sends it for review.",
    dropHint: "Drag files here or click to browse",
    dropSubhint: "PDF, Excel, CSV, and images supported",
    chooseTypeFirst: "Choose a document type above before uploading.",
    processing: "Processing your files…",
    noTemplates: "Ask your team to configure document types, or switch to Expert mode.",
  },
  review: {
    title: "Approval queue",
    subtitle: "Review extracted values before they flow into your report. Override only when you know the source supports it.",
    overrideRequired: "Please explain why you're overriding extracted values.",
    rejectRationale: "Rejection reason (required)",
  },
  evidence: {
    title: "Evidence & activity",
    subtitle: "See how source documents became report-ready disclosures.",
  },
  report: {
    chooseFramework: "Choose your reporting framework",
    buildSections: "Build report sections",
    verifyPublish: "Verify & publish",
    stickyPublish: "Ready to publish?",
  },
  steps: {
    setup: "Set up",
    upload: "Upload",
    review: "Review",
    publish: "Publish",
  },
  trust: {
    verified: "Verified",
    securing: "Securing…",
    pending: "Pending",
    viewEvidence: "View evidence",
    cryptographicProof: "Cryptographic proof",
    evidenceTrail: "Activity & evidence trail",
    howWeGotThis: "How we got this number",
    verificationSummary: "Verification summary",
  },
  nav: {
    home: "Home",
    thisPeriod: "This period",
    upload: "Upload",
    documents: "Documents",
    report: "Report",
    evidence: "Evidence",
    approvalQueue: "Approval queue",
    documentTypes: "Document types",
    evidenceTrail: "Evidence trail",
    teamTools: "Team tools",
    advanced: "Advanced tools",
    help: "Help",
    members: "Team",
  },
  expert: {
    uploadTitle: "Upload & process",
    uploadSubtitle: "Upload source files by document type. Atlas secures each file and prepares values for review.",
    uploadQueue: "Upload queue",
    chooseDocumentType: "Choose document type",
    documentTypesReady: "Document types ready",
    documentsProcessed: "Documents processed",
    previewExtraction: "Preview extraction",
    confirmExtraction: "Confirm extraction",
    previewSummary: "Preview summary",
    fieldsFound: "Fields found",
    fieldsMissing: "Fields missing",
    projectedMetrics: "Projected metrics",
    needsAttention: "Needs attention",
    documentTypeHealth: "Document type health",
    approveAllContinue: "Approve all and continue",
    clearHighlight: "Clear highlight",
    sourceTrail: "Source trail",
    viewDetails: "View details",
    technicalDetails: "Technical details",
    showTechnicalDetails: "Show technical details",
    fieldKeys: "Field keys",
    rawExport: "Raw export",
    metricsTitle: "Metrics",
    metricsSubtitle: "Verified numbers ready for your report.",
    reportMetrics: "Report metrics",
    sourceValues: "Source values",
    intelligenceFeed: "Recommendations",
    documentTypesTitle: "Document types",
    documentTypesSubtitle: "Define what Atlas extracts from each kind of source file.",
    thisPeriod: "This period",
    organizationWide: "Organization-wide",
    fieldName: "Field name",
    whatToExtract: "What to extract",
    activitySummary: "Activity summary",
    whatHappened: "What happened",
    verificationDetails: "Verification details",
    fileFingerprint: "File fingerprint",
    onChainReference: "On-chain reference",
    verificationHint: "This file hasn't been changed since upload.",
    pipelineSubtitle: "Upload → Secure → Review → Metrics",
    openInApprovalQueue: "Open in approval queue",
    accessRoles: "Access roles",
  },
  modes: {
    simple: "Simple",
    expert: "Expert",
    simpleHint: "Guided workflows for reporting leads",
    expertHint: "Full pipeline, document types, and team tools",
    lead: "Lead",
    operator: "Operator",
    reviewer: "Reviewer",
  },
  roles: {
    company_owner: "Organization owner",
    sustainability_manager: "Sustainability manager",
    data_reviewer: "Data reviewer",
    report_viewer: "Report viewer",
    system_admin: "System administrator",
  },
} as const;

export const glossary = [
  {
    term: "Reporting period",
    definition: "A time-bound workspace for one sustainability report (e.g. FY2025).",
  },
  {
    term: "Verified",
    definition: "Source documents are fingerprinted and anchored so changes after upload can be detected.",
  },
  {
    term: "Report readiness",
    definition: "Combined progress across uploads, reviews, metrics, and report sections.",
  },
  {
    term: "Evidence trail",
    definition: "The path from uploaded file through review to numbers in your published report.",
  },
  {
    term: "Document type",
    definition: "A configured pattern for a kind of source file (e.g. electricity bill) and the fields Atlas extracts from it.",
  },
  {
    term: "Source trail",
    definition: "How a report number links back to a specific field in a specific uploaded document.",
  },
  {
    term: "Verification details",
    definition: "Technical proof that a file was fingerprinted at upload and has not changed since.",
  },
] as const;
