/**
 * Auto-generated TypeScript types from backend OpenAPI schema.
 * DO NOT EDIT — regenerated by: npx openapi-typescript http://localhost:8000/openapi.json -o src/types/api.generated.ts
 *
 * Placeholder until the OpenAPI codegen pipeline runs in Wave 2.
 */

// ── Shared Envelopes ────────────────────────────────────────
export interface ApiEnvelope<T = unknown> {
  success: boolean;
  data: T;
  meta: {
    request_id: string;
    timestamp: string;
  };
}

export interface ApiError {
  success: false;
  error: {
    code: string;
    message: string;
    details: Array<{ field?: string; issue: string }>;
  };
  meta: {
    request_id: string;
    timestamp: string;
  };
}

export interface PaginatedResponse<T = unknown> {
  success: boolean;
  data: T[];
  pagination: {
    page: number;
    page_size: number;
    total: number;
    has_next: boolean;
  };
  meta: {
    request_id: string;
    timestamp: string;
  };
}

// ── SSE ─────────────────────────────────────────────────────
export interface SseEventEnvelope {
  event_type: "queued" | "started" | "progress" | "record_complete" | "section_complete" | "completed" | "failed";
  entity_type: string;
  entity_id: string;
  sequence: number;
  timestamp: string;
  payload: Record<string, unknown>;
}

// ── Health ──────────────────────────────────────────────────
export interface HealthResponse {
  status: string;
  version: string;
  environment: string;
  database?: string;
}
